greeting:
  message: "hello"

quarkus:
  native:
    resources:
      includes: publicKey.pem
  mongodb:
    connection-string: mongodb+srv://lotl:ITMMkQMxFwBTNnPl@cluster0.uvg2i.mongodb.net/lotl?retryWrites=true&w=majority
    database: "lotl"
  grpc:
    server:
      port: 9000
  http:
    port: 8000
  token:
    id: "617ad0ac07f435995daecf96"
kafka.bootstrap.servers: 103.56.156.179:9092
mp.messaging.incoming.contract-events.connector: smallrye-kafka

smallrye:
  jwt:
    token:
      kid: Metadefi
#    decrypt:
#      key:
#        location: privateKey.pem
#      algorithm: RSA_OAEP_256
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: https://metadefi.land
#    decrypt:
#      key:
#        location: privateKey.pem

"%dev":
  quarkus:
    mongodb:
      connection-string: mongodb+srv://lotl:ITMMkQMxFwBTNnPl@cluster0.uvg2i.mongodb.net/lotl?retryWrites=true&w=majority
      database: "lotl"
    grpc:
      server:
        port: 9001
    http:
      port: 8081
  token:
    id: "617ad0ac07f435995daecf96"
  kafka.bootstrap.servers: 103.56.156.179:9092
  mp.messaging.incoming.contract-events.connector: smallrye-kafka